import = [
    "~/.config/alacritty/catppuccin-mocha.toml"
]

[font]
normal = { family = "JetBrains Mono Nerd Font", style = "Bold" }
bold = { family = "JetBrains Mono Nerd Font", style = "Bold" }
italic = { family = "JetBrains Mono Nerd Font", style = "Italic" }

[env]
TERM = "xterm-256color"

# [window]
# opacity = 0.9

